server:
  port: 80

spring:
  application:
  name: C99 Innovation Management
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:innovationdb
    username: sa
    password: password
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        metadata_builder_contributor: com.c99.innovation.common.SQLFunctionsMetadataBuilderContributor
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${java.io.tmpdir}

innovation:
  jwt:
    secret_salt: Innovation@123456
    jwt_validity: 3600000 # 1000 * 60 * 60 - 1 Hour
    jwt_issuer: Innovation_New_Project
    refresh_expiration: 360000000 # 1000 * 60 * 60 * 100- 100 Hour

aws:
  access_key_id: AKIAV3KWG2VTG47Q667Q
  secret_access_key: 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
  s3:
    bucket: innovation-management
    region: ap-southeast-1

