# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  repositories:
    - repository: innovation.fe
      type: git
      ref: main
      name: innovation.fe
    - repository: Innovation.BE
      type: git
      ref: main
      name: Innovation.BE

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: innovation.fe
  - checkout: Innovation.BE
  - task: Maven@3
    inputs:
      mavenPomFile: 'Innovation.BE/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: '-Ptest clean install package -DskipTests'
